#!/system/bin/sh
# Root-side helper for webroot/index.html.
#
# KernelSU/ReSukiSU WebUI pages are static files, not CGI pages.  Keeping all
# file I/O in this small script lets the page use the manager's `ksu.exec()`
# bridge without opening an unauthenticated localhost root HTTP service.

SCRIPT_DIR=${0%/*}
[ "$SCRIPT_DIR" = "$0" ] && SCRIPT_DIR=.
MODDIR=$(CDPATH= cd "$SCRIPT_DIR" 2>/dev/null && pwd)
[ -n "$MODDIR" ] || exit 1
STATE_DIR=${XBS_STATE_DIR:-/data/local/tmp/XtremeBS}
CONF=${XBS_CONF:-$STATE_DIR/XtremeBS.conf}
STATUS_FILE="$STATE_DIR/XtremeBS.status"
SERVICE_LOG="$STATE_DIR/XtremeBS.service.log"
CTL="$MODDIR/system/bin/XBSctl"
DAEMON="$MODDIR/system/bin/XtremeBSd"
CPU_ROOT=${XBS_CPU_BASE_PATH:-/sys/devices/system/cpu}

fail() {
  # ksu.exec() returns stdout to the page, so errors belong on stdout too.
  printf 'ERROR: %s\n' "$*"
  exit 1
}

ensure_state_dir() {
  mkdir -p "$STATE_DIR" 2>/dev/null || fail "cannot create $STATE_DIR"
}

get_conf_value() {
  awk -v key="$1" '
    /^[[:space:]]*#/ { next }
    index($0, key "=") == 1 {
      sub(/^[^=]*=/, "")
      print
      exit
    }
  ' "$CONF" 2>/dev/null
}

starter_config() {
  cat <<EOF
# XtremeBS v2 configuration
# Save this file, then change one setting at a time and press Reload.
version=2
delay=3
log_file=$STATE_DIR/XtremeBS.log
log_level=1
notify=true

boot={
}

charging={
}

low_power={
# keep_on_charge=true
}

screen_off={
}

manual={
}
EOF
}

decode_base64_to_file() {
  encoded=$1
  output=$2
  candidate="${output}.decoded"
  rm -f "$candidate"

  if command -v base64 >/dev/null 2>&1 && printf '%s' "$encoded" | base64 -d > "$candidate" 2>/dev/null; then
    mv -f "$candidate" "$output"
    return 0
  fi
  rm -f "$candidate"
  if command -v toybox >/dev/null 2>&1 && printf '%s' "$encoded" | toybox base64 -d > "$candidate" 2>/dev/null; then
    mv -f "$candidate" "$output"
    return 0
  fi
  rm -f "$candidate"
  if [ -x /data/adb/ksu/bin/busybox ] && printf '%s' "$encoded" | /data/adb/ksu/bin/busybox base64 -d > "$candidate" 2>/dev/null; then
    mv -f "$candidate" "$output"
    return 0
  fi
  rm -f "$candidate"
  if [ -x /data/adb/magisk/busybox ] && printf '%s' "$encoded" | /data/adb/magisk/busybox base64 -d > "$candidate" 2>/dev/null; then
    mv -f "$candidate" "$output"
    return 0
  fi
  return 1
}

reload_daemon() {
  if [ ! -x "$CTL" ]; then
    printf 'ERROR: controller is missing: %s\n' "$CTL"
    return 1
  fi
  result=$("$CTL" reload 2>&1)
  rc=$?
  if [ "$rc" -ne 0 ]; then
    printf 'ERROR: reload could not be queued: %s\n' "$result"
    return "$rc"
  fi
  printf '%s\n' "$result"
}

save_config() {
  encoded=${1:-}
  [ -n "$encoded" ] || fail "no configuration data was supplied"
  case "$encoded" in
    *[!A-Za-z0-9+/=]*) fail "configuration encoding was invalid" ;;
  esac
  # A WebUI config should be tiny; this protects the root bridge from an
  # accidental paste of a giant file while leaving ample room for comments.
  [ "${#encoded}" -le 524288 ] || fail "configuration is too large"

  ensure_state_dir
  umask 077
  tmp="${CONF}.tmp.$$"
  rm -f "$tmp"
  decode_base64_to_file "$encoded" "$tmp" || fail "no compatible base64 decoder was found"
  [ -s "$tmp" ] || { rm -f "$tmp"; fail "refusing to save an empty configuration"; }
  mv -f "$tmp" "$CONF" || { rm -f "$tmp"; fail "cannot write $CONF"; }
  chmod 600 "$CONF" 2>/dev/null || true
  if ! result=$(reload_daemon); then
    fail "configuration was saved, but reload could not be queued: ${result#ERROR: }"
  fi
  printf 'Configuration saved. %s\n' "$result"
}

cpu0_only_preset() {
  ensure_state_dir
  cores=""
  for node in "$CPU_ROOT"/cpu[0-9]*/online; do
    [ -f "$node" ] || continue
    cpu=${node%/online}
    cpu=${cpu##*/}
    [ "$cpu" = cpu0 ] || cores="$cores $cpu"
  done
  cores=${cores# }
  [ -n "$cores" ] || fail "this kernel exposes no hotpluggable CPU online nodes"

  umask 077
  tmp="${CONF}.tmp.$$"
  cat > "$tmp" <<EOF
# CPU0-only screen-off preset generated by XtremeBS WebUI.
# WARNING: this is intentionally aggressive. The kernel may refuse some CPUs.
# Core 0 is never listed and is therefore kept online.
version=2
delay=1
log_file=$STATE_DIR/XtremeBS.log
log_level=2
notify=false

boot={
}

charging={
}

low_power={
}

screen_off={
  disable_cores=$cores
}

manual={
}
EOF
  chmod 600 "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$CONF" || { rm -f "$tmp"; fail "cannot write $CONF"; }
  if ! result=$(reload_daemon); then
    fail "CPU0-only preset was saved, but reload could not be queued: ${result#ERROR: }"
  fi
  printf 'Applied CPU0-only screen-off preset. Target cores: %s\n%s\n' "$cores" "$result"
}

show_status() {
  if [ -f "$STATUS_FILE" ]; then
    cat "$STATUS_FILE"
  else
    printf 'Status is not available yet. The daemon may still be starting.\n'
  fi
}

show_log() {
  log_file=$(get_conf_value log_file)
  [ -n "$log_file" ] || log_file="$STATE_DIR/XtremeBS.log"
  if [ -f "$log_file" ]; then
    # A bounded response keeps the WebView responsive even with an old large log.
    tail -n 500 "$log_file" 2>/dev/null || cat "$log_file"
  else
    printf 'No daemon log at %s\n' "$log_file"
    [ -f "$SERVICE_LOG" ] && {
      printf '\nService startup log:\n'
      tail -n 100 "$SERVICE_LOG" 2>/dev/null || cat "$SERVICE_LOG"
    }
  fi
}

diagnostics() {
  printf 'Module directory: %s\n' "$MODDIR"
  printf 'State directory:  %s\n' "$STATE_DIR"
  printf 'Daemon file:      %s\n' "$DAEMON"
  if command -v pgrep >/dev/null 2>&1 && pgrep -f "$DAEMON" >/dev/null 2>&1; then
    printf 'Daemon process:   running\n'
  else
    printf 'Daemon process:   not detected\n'
  fi
  printf 'Screen source:    %s\n' "$(dumpsys deviceidle get screen 2>&1 | head -n 1)"
  printf 'Power fallback:   %s\n' "$(dumpsys power 2>/dev/null | grep -m 1 -E 'mWakefulness=|Display Power: state=')"
  printf '\nCPU online nodes:\n'
  printf 'cpu0: %s\n' "$(cat "$CPU_ROOT/cpu0/online" 2>/dev/null || printf 'online (boot CPU / no node)')"
  for node in "$CPU_ROOT"/cpu[0-9]*/online; do
    [ -f "$node" ] || continue
    cpu=${node%/online}
    cpu=${cpu##*/}
    printf '%s: %s\n' "$cpu" "$(cat "$node" 2>/dev/null)"
  done
  if [ -f "$SERVICE_LOG" ]; then
    printf '\nLast service messages:\n'
    tail -n 20 "$SERVICE_LOG" 2>/dev/null || true
  fi
}

queue_command() {
  action=${1:-}
  event=${2:-}
  case "$action" in
    reload|pause|resume|safe)
      [ -z "$event" ] || fail "$action does not accept an event name"
      ;;
    start|stop)
      if [ -n "$event" ]; then
        case "$event" in ''|[!A-Za-z]*|*[!A-Za-z0-9_.-]*) fail "invalid event name" ;; esac
      fi
      ;;
    *) fail "unsupported command: $action" ;;
  esac
  [ -x "$CTL" ] || fail "controller is missing: $CTL"
  if [ -n "$event" ]; then
    "$CTL" "$action" "$event" 2>&1
  else
    "$CTL" "$action" 2>&1
  fi
}

case ${1:-} in
  get-config) [ -f "$CONF" ] && cat "$CONF" || starter_config ;;
  save-config) save_config "${2:-}" ;;
  cpu0-preset) cpu0_only_preset ;;
  get-status) show_status ;;
  get-log) show_log ;;
  diagnostics) diagnostics ;;
  command) shift; queue_command "$@" ;;
  *)
    cat <<'EOF'
XtremeBS WebUI helper
Usage: xbs-webui.sh {get-config|save-config BASE64|cpu0-preset|get-status|get-log|diagnostics|command ACTION [EVENT]}
EOF
    ;;
esac
